"""update name

Revision ID: 7f89a2654424
Revises: 715187c5bf79
Create Date: 2026-07-26 18:18:16.899749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f89a2654424'
down_revision: Union[str, Sequence[str], None] = '715187c5bf79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'hased_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hased_password', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
